# YOLOv8n Model Configuration

# Model architecture
backbone:
  type: CSPDarknet
  depth_multiple: 0.33
  width_multiple: 0.25
  layers:
    - type: Conv
      args:
        filters: 32
        kernel_size: 3
        stride: 1
    - type: CSP
      args:
        filters: 64
        n: 3
    - type: SPP
      args:
        filters: 128

# Head architecture
head:
  type: Detect
  anchors: [10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326]
  depthwise: False

# Training hyperparameters
train:
  img_size: 640
  batch_size: 16
  epochs: 14
  lr0: 0.01
  lrf: 0.2
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  dfl: 1.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
